export const TEXT_FIELD = 'TEXT_FIELD';
export const LINK_FIELD = 'LINK_FIELD';
export const PASSWORD_FIELD = 'PASSWORD_FIELD';
export const INPUT_TEXT_FIELD = 'INPUT_TEXT_FIELD';
export const INPUT_PASSWORD_FIELD = 'INPUT_PASSWORD_FIELD';
